name: 完全なテストパイプライン

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ドメイン層のテスト
  domain:
    uses: ./.github/workflows/domain-test.yml
  # インフラストラクチャ層のテスト
  infrastructure:
    uses: ./.github/workflows/infrastructure-test.yml  
  # アプリケーション層のテスト
  application:
    uses: ./.github/workflows/application-test.yml
  #　インターフェイス層のテスト
  interface:
    uses: ./.github/workflows/interface-test.yml